import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  OpportunityMapSchema,
  CURRENT_OPPORTUNITY_MAP_VERSION,
} from "../opportunityMap";

/**
 * A minimal but realistic base map, shaped like `buildOpportunityMap`'s
 * (`lib/match.ts`) real output — used by the schema-reconcile regression
 * tests below. Callers spread/override fields per-test.
 */
function baseLiveMap() {
  return {
    version: CURRENT_OPPORTUNITY_MAP_VERSION,
    profile: { description: "A biotech startup doing R&D." },
    followUps: [],
    summary: { highPotential: 1, fundingIdentified: 500000, agencies: 1, closingIn90Days: 0 },
    matches: [
      {
        opportunity: {
          id: "opp-1",
          program: "SBIR Phase I",
          agency: "NIH",
          kind: "grant",
          description: "desc",
          eligibility: "small business",
          source: "sbir",
        },
        tier: "likely",
        score: 82,
        criteria: [],
        // The model legitimately omitted whyIneligible — a clear fit has
        // nothing "ineligible" to report (lib/claude.ts's parseJson() never
        // validates the LLM's JSON, so this is a real, reachable shape).
        whyFit: "Strong alignment with NIH priorities.",
        whatToVerify: "Confirm SAM.gov registration.",
        whatToDoNext: "Reach out to the program officer.",
        eligibility: {
          determination: {
            opportunity_id: "opp-1",
            bucket: "eligible",
            satisfied_rules: [],
            failed_rules: [],
            unknown_rules: [],
            required_steps: [],
          },
          freshness: {
            data_as_of: "2026-08-01T00:00:00.000Z",
            is_stale: false,
            caveat: null,
            assessed_at: "2026-08-15T00:00:00.000Z",
          },
        },
      },
    ],
    agencyIntelligence: [],
    costDebug: {
      stages: [
        {
          stage: "profile_extraction",
          provider: "anthropic",
          model: "claude-haiku",
          inputTokens: 100,
          outputTokens: 50,
          costUsd: 0.001,
          latencyMs: 500,
          calls: 1,
        },
      ],
      totalCostUsd: 0.01,
      totalLatencyMs: 1234,
      pricingAsOf: "2026-01-01",
    },
  };
}

const here = dirname(fileURLToPath(import.meta.url));
const precomputed = JSON.parse(
  readFileSync(join(here, "../../../data/precomputed.json"), "utf8"),
) as Array<{ key: string; id: string; map: unknown }>;

/**
 * §3.6 — the OpportunityMap version tag must be ADDITIVE: every cached response
 * in data/precomputed.json must still validate whether or not it carries the
 * tag. (Maps regenerated by the current `buildOpportunityMap` DO stamp
 * `version`, since §3.6 made the builder write it on every live map; older
 * frozen maps predate it. Both must validate.) This is the CON-01 escalation
 * guard turned into a test.
 */

test("every cached precomputed map validates against the formalized schema", () => {
  assert.ok(precomputed.length >= 4, "expected the 4 judged cases");
  for (const entry of precomputed) {
    const res = OpportunityMapSchema.safeParse(entry.map);
    assert.equal(
      res.success,
      true,
      `cached map '${entry.key}' failed: ${res.success ? "" : JSON.stringify(res.error.issues.slice(0, 3))}`,
    );
  }
});

test("a cached map with no version tag validates (version is optional / additive)", () => {
  // The tag is optional/additive: a map WITHOUT it must validate and parse with
  // `version === undefined`. Derive an explicitly-unstamped map by stripping any
  // version the current builder now stamps, so this asserts schema optionality
  // rather than depending on whether the frozen fixture predates the tag.
  const { version: _drop, ...unstamped } = precomputed[0].map as { version?: unknown };
  const parsed = OpportunityMapSchema.parse(unstamped);
  assert.equal(parsed.version, undefined);
});

test("a producer can stamp the current version without breaking the schema", () => {
  const stamped = { ...(precomputed[0].map as object), version: CURRENT_OPPORTUNITY_MAP_VERSION };
  const parsed = OpportunityMapSchema.parse(stamped);
  assert.equal(parsed.version, CURRENT_OPPORTUNITY_MAP_VERSION);
});

/**
 * schema-reconcile — the API boundary's `logMapDrift()` (`app/api/match/handler.ts`)
 * runs `OpportunityMapSchema.safeParse(map)` on every real search purely for
 * observability. Before this reconcile, a LIVE map failed that parse on two
 * counts: (1) it declares `matches[].eligibility` / top-level `costDebug`,
 * additive fields the v1 schema never declared, and (2) `lib/match.ts` assigns
 * the four narrative `Match` strings straight from an unvalidated LLM JSON
 * response, so any of them can legitimately be `undefined`. These three tests
 * lock in the fix.
 */

test("(a) a realistic live map — eligibility + costDebug + an omitted narrative field — validates", () => {
  const live = baseLiveMap();
  const res = OpportunityMapSchema.safeParse(live);
  assert.equal(
    res.success,
    true,
    `live-shaped map failed: ${res.success ? "" : JSON.stringify(res.error.issues)}`,
  );
  if (res.success) {
    // whyIneligible was omitted by the "model" in the fixture; the schema
    // must default it to "" rather than reject the map.
    assert.equal(res.data.matches[0].whyIneligible, "");
    assert.ok(res.data.matches[0].eligibility, "eligibility should survive parsing");
    assert.ok(res.data.costDebug, "costDebug should survive parsing");
  }
});

test("(b) a cached/precomputed-shaped map — no eligibility, no costDebug, all narrative fields present — still validates", () => {
  const live = baseLiveMap();
  const cached: any = { ...live };
  delete cached.costDebug;
  cached.matches = live.matches.map(({ eligibility, ...rest }) => ({
    ...rest,
    // v1 cached shape: every narrative field present (nothing omitted).
    whyIneligible: "No major concerns identified.",
  }));
  delete cached.version;
  const res = OpportunityMapSchema.safeParse(cached);
  assert.equal(
    res.success,
    true,
    `cached-shaped map failed: ${res.success ? "" : JSON.stringify(res.error.issues)}`,
  );
  if (res.success) {
    assert.equal(res.data.matches[0].eligibility, undefined);
    assert.equal(res.data.costDebug, undefined);
  }
});

test("(c) a genuinely malformed map (summary missing) still fails", () => {
  const malformed: any = baseLiveMap();
  delete malformed.summary;
  const res = OpportunityMapSchema.safeParse(malformed);
  assert.equal(res.success, false, "a map missing `summary` must still fail validation");
});

test("(c) a genuinely malformed map (wrong-typed required field) still fails", () => {
  const malformed: any = baseLiveMap();
  malformed.summary.highPotential = "one"; // should be a number
  const res = OpportunityMapSchema.safeParse(malformed);
  assert.equal(res.success, false, "a map with a wrong-typed `summary.highPotential` must still fail validation");
});

test("(c) an excluded eligibility determination driven solely by model_inferred rules still fails (R8.4 intact)", () => {
  const malformed: any = baseLiveMap();
  malformed.matches[0].eligibility.determination.bucket = "excluded";
  malformed.matches[0].eligibility.determination.failed_rules = [
    {
      rule_id: "some-rule",
      category: "size_ownership",
      description: "some rule",
      provenance: "model_inferred",
    },
  ];
  const res = OpportunityMapSchema.safeParse(malformed);
  assert.equal(
    res.success,
    false,
    "declaring `eligibility` in the schema must not weaken the R8.4 anti-fabrication refinement",
  );
});
